name: TestPlugin
main: io.github.cjbell630.testplugin.TestPlugin
version: 0.0.1
commands:
  basic:
    description: This is a demo command.
    usage: /basic
    permission: TestPlugin.basic
    permission-message: You don't have TestPlugin.basic
  name:
    description: Name the currently held item.
    usage: /name [name]
    permission: TestPlugin.name
    permission-message: You don't have TestPlugin.basic
  permissions:
    basic:
      description: Use basic command
      default: true
    name:
      description: Use name command
      default: true